version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: exowars-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exowars
      MYSQL_USER: exowars_user
      MYSQL_PASSWORD: exowars_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - exowars-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    container_name: exowars-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - exowars-network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    networks:
      - exowars-network

volumes:
  mysql_data:
  dynamodb_data:


networks:
  exowars-network:
    driver: bridge
