version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: exowars-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exowars
      MYSQL_USER: exowars_user
      MYSQL_PASSWORD: exowars_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: exowars-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql-data:
